### ISSUE TITLE
Add a command-line option to override the `no-dev-version` configuration parameter

### ISSUE THREAD

**Issue by breard-r** [crate-ci/cargo-release#141]
Currently, when the `no-dev-version` configuration parameter is set to false (which is the default), it is possible to use the `--no-dev-version` CLI argument to override it to true. However, the reverse operation is not supported: if `no-dev-version` is set to true in the configuration, there is no CLI argument that can override it to false. It would be nice to add a flag (`--dev-version`? `--force-dev-version`?) that adds such possibility.
It would also be nice that, if the `--dev-version-ext` CLI argument is specified, the `no-dev-version` is also forced to false. Having the possibility to force `no-dev-version` to false with `--dev-version-ext` would not deprecate the need of `--dev-version`/`--force-dev-version` since it requires to specify the `dev-version-ext` while the additional flag would make use of the default value.

A temporary workaround is to have a copy of the configuration file with `no-dev-version` set to false and use it with the `-c`/`--config` CLI argument ; but this is quite cumbersome.

**Comment by epage** [comment]
Good point! We don't have a positive flag for this so it can't be overridden.

**Comment by epage** [comment]
We now have both flags.
