### ISSUE TITLE
Add the `--update-only` and `--update-only-dev` flags in the CLI

### ISSUE THREAD

**Issue by breard-r** [crate-ci/cargo-release#142]
The `--update-only` flag would combine the `--skip-push`, `--skip-tag`, `--skip-publish` and `--no-dev-version` flags.
The `--update-only-dev` would combine the `--skip-push`, `--skip-tag` and `--skip-publish` flags. It would also force `no-dev-version` to false. Also, it should do only one version bump instead of two.

## Examples

```
$ grep version Cargo.toml
version = "0.2.0"
$ cargo release minor --update-only
$ grep version Cargo.toml
version = "0.3.0"
$ cargo release patch --update-only
$ grep version Cargo.toml
version = "0.3.1"
```

```
$ grep version Cargo.toml
version = "0.2.0"
$ cargo release patch --update-only-dev
$ grep version Cargo.toml
version = "0.2.1-alpha.0"
$ cargo release minor --update-only-dev
$ grep version Cargo.toml
version = "0.3.0-alpha.0"
```

## Use case

As noted in #99, when publishing a new version you don't know yet what the next version will be. Sometimes your planning is telling you that right after a release you'll have to implement some changes that will requires a major or minor release, hence you do not want to start a patch release. And if your CI-platform or QA team reports a regression you have to patch right away, having the possibility to directly set the next dev version as a major or minor release would have been a mistake.

Setting `no-dev-version` to true solves the first part of the problem by letting you decide later. This is where the `--update-only-dev` flags comes handy since it allows you to start the next development iteration with the correct version number.
The `--update-only` is simply be a shortcut for people who does not uses dev versions.

**Comment by breard-r** [comment]
By the way, no, using `cargo release alpha --skip-push --skip-tag --skip-publish --no-dev-version` would not do the trick because it cannot make use of any custom `dev-version-ext`.

```
$ grep dev-version-ext release.toml
dev-version-ext = "dev"
$ grep version Cargo.toml
version = "0.2.0"
$ cargo release patch --update-only-dev
$ grep version Cargo.toml
version = "0.2.1-dev"
```

**Comment by sunng87** [comment]
I found this makes sense. Typically you don't have much idea about what level to bump after a release. For example, after releasing `1.1.0`, should we make it `2.0.0-alpha.0` or `1.1.1-alpha.0`? This is up to your decision later. So it's ok to keep patch level bump by default.

But when I actually want to start 2.0.0 development, I will have manually update versions to some 2.0 alpha or beta. It would be nice if `cargo-release` could help in this process.

**Comment by razvan** [comment]
Updating versions is what all projects using `cargo-release` need. This fundamental functionality could be nicely exposed to the user without any git mangling. There should be an easy and straightforward way to just bump versions or provide them over the command line.

**Comment by epage** [comment]
My plan is to implement this in `cargo-edit` (https://github.com/killercup/cargo-edit/issues/338) and work to get it upstream in `cargo` one day (like `cargo-add` moving to cargo, see https://github.com/rust-lang/cargo/issues/5586)

**Comment by epage** [comment]
Closing in favor of cargo-edit
