### ISSUE TITLE
cargo release --continue

### ISSUE THREAD

**Issue by emschwartz** [crate-ci/cargo-release#173]
If publishing one crate in a workspace fails for any reason, it halts the `cargo release` process. It would be nice if there were a way to run something like `cargo release --continue` or `cargo release --from-package=<the one that failed>` to have it continue the release process from where it left off. Right now I think the best option is to manually specify crates to exclude, but in a project with a lot of crates, that can be pretty annoying.

**Comment by epage** [comment]
What kind of failures do you commonly see?  I'm wondering if I can tailor some other changes I'm working on to help make recovery easier.

**Comment by epage** [comment]
Currently, we run through all the release steps on a given crate before moving on.  I'm looking at switching us to performing a step on all crates before moving on.  I was hoping it would help but I'm unsure.  I think it'll at least make a `--continue` easier to implement.  One challenge is knowing where we left off when bumping.  With my change, all version bumping will be completed so we won't have that problem.  `--continue` would just skip that step and try to publish the crates if they weren't already published.

**Comment by hrydgard** [comment]
I ran into this:

```
$ cargo release minor
Release physx-sys 0.3.0? [y/N]
y
[2020-03-04T10:56:25Z INFO ] Update physx-sys to version 0.3.0
[2020-03-04T10:56:25Z INFO ] Fixing physx's dependency on physx-sys to `^0.3` (from `^0.2`)
warning: LF will be replaced by CRLF in physx-sys/Cargo.toml.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in physx/Cargo.toml.
The file will have its original line endings in your working directory
[master a81236d] (cargo-release) version 0.3.0
 2 files changed, 2 insertions(+), 2 deletions(-)
[2020-03-04T10:56:25Z INFO ] Running cargo publish on physx-sys
    Updating crates.io index
   Packaging physx-sys v0.3.0 (C:\dev\physx-rs\physx-sys)
   Verifying physx-sys v0.3.0 (C:\dev\physx-rs\physx-sys)
   Compiling cc v1.0.50
   Compiling cmake v0.1.42
   Compiling physx-sys v0.3.0 (C:\dev\physx-rs\target\package\physx-sys-0.3.0)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 08s
   Uploading physx-sys v0.3.0 (C:\dev\physx-rs\physx-sys)
[2020-03-04T11:00:10Z WARN ] Fatal: Timeout waiting for crate to be published.
```

The crate was actually published, though. I just now want cargo-release to perform the last few steps after that step, but can't.

**Comment by halzy** [comment]
I'm seeing the same timeout error, on OSX. 

```
Uploading stream_multiplexer v0.10.0 (/Users/bhalsted/src/stream_multiplexer)
[2020-03-13T03:11:32Z INFO ] Waiting for publish to complete...
[2020-03-13T03:12:03Z WARN ] Fatal: Timeout waiting for crate to be published.
```

**Comment by tylerhawkes** [comment]
I'm seeing the `Waiting for publish to complete...` error on linux while publishing to cloudsmith.

**Comment by epage** [comment]
#393 will allow a `cargo release` (no level / target version) will now resume the release and not re-publish previously published crates.

I believe this now resolves the needs for a `--continue` (though its only in `master` for now, hoping to release soon).  If this doesn't work out for people, please file new issues about your specific errors and how `cargo release` didn't fix it.
