### ISSUE TITLE
Error detecting clean working directory

### ISSUE THREAD

**Issue by dbcfd** [crate-ci/cargo-release#195]
```
$ HEAD_OUTPUT=$(git diff HEAD --exit-code --name-only)
$ echo Head Output=$HEAD_OUTPUT
Head Output=
$ LS_OUTPUT=$(git ls-files --exclude-standard --others)
$ echo LS Output=$LS_OUTPUT
LS Output=
$ RUST_LOG=trace cargo release --no-confirm --no-dev-version --tag-name "{{crate_name}}-{{prev_version}}" -vv patch
[2019-12-18T18:51:27Z WARN ] Uncommitted changes detected, please commit before release.
```

Git status also indicates a clean working directory. Not sure what it is error'ing on.

**Comment by dbcfd** [comment]
This was actually due to the CI environment and a hidden directory, having files on git ls-files. Not sure how to marry this up with the git status output.

**Comment by dbcfd** [comment]
Even with these files in .gitignore, they still show up as uncomitted.

**Comment by epage** [comment]
Here are the checks that we perform
https://github.com/sunng87/cargo-release/blob/master/src/git.rs#L10

**Comment by dbcfd** [comment]
Yeah, I've been trying to figure out how resolve the output from those commands with what the environment has. The path it tells me is causing what is dirty (I forked and added debugging) doesn't seem to exist, so something is possibly going on with the command and the filesystem interaction.

**Comment by dbcfd** [comment]
Downgrading to 0.12.4 fixes the issue. Going to do a PR to make dirty via untracked optional.

**Comment by epage** [comment]
Here is publishes logic
https://github.com/rust-lang/cargo/blob/d8106473c16cad67574ac334759bc10a70b572d9/src/cargo/ops/cargo_package.rs#L228

**Comment by TotalKrill** [comment]
I ran into this issue today as well it seems

**Comment by TotalKrill** [comment]
Downgrading did not work for me, so is probably another issue

**Comment by epage** [comment]
We're adding logging so we can at least tell what is causing cargo-release to think things are dirty

**Comment by epage** [comment]
Are you using submodules?  That seems to be the cause in #416

**Comment by edeustace** [comment]
Seeing this on AWS Codebuild running windows using a codestar connection. The list contains all files in the repo with status `WT_DELETED`.
