### ISSUE TITLE
Integrate with github commandline tool for release creation

### ISSUE THREAD

**Issue by sunng87** [crate-ci/cargo-release#230]
The github command line tool provides [a `release` command](https://cli.github.com/manual/gh_release_create) to create a github release. It would be nice if you optionally support it in our process.

Related topics:

- [ ] changelog #231 
- [ ] artifact/binary upload #201

**Comment by sunng87** [comment]
@epage right, I think it's an optional one. Most binaries are platform dependent so the workflow should be using [gh release upload](https://cli.github.com/manual/gh_release_upload) to upload them individually.

I just changed *prerequisites* to *related topics* to clarify.

**Comment by CleanCut** [comment]
I would love this functionality even without any binary artifact handling.

**Comment by epage** [comment]
For those interested, for now I've taken to creating the release, with notes, via Github Actions

See https://github.com/crate-ci/typos/commit/5c92dc6f8cc68b9d1c8cb1e8840b81e78cf7f65d

**Comment by CleanCut** [comment]
@epage Thanks for sharing!

**Comment by epage** [comment]
Decided to handle this by documenting it in the FAQ
