### ISSUE TITLE
Sign tar ball

### ISSUE THREAD

**Issue by kpcyrd** [crate-ci/cargo-release#235]
My old workflow included manually executing the following steps:
```
git archive --prefix=rebuilderd-0.5.0/ -o /some/path/rebuilderd-0.5.0.tar.gz v0.5.0
cd /some/path/
gpg --armor --detach-sign -u redacted@example.com rebuilderd-0.5.0.tar.gz
```
The tar ball is identical to the tar ball generated by github, so I'm just uploading the signature to the github release. Instead of a global path I could imagine using a folder in the repo that's listed in `.gitignore`.

This might depend on #234.

**Comment by epage** [comment]
Could this be done with a hook?

**Comment by epage** [comment]
As tar balls aren't part of the current `cargo-release` process, I'm closing this out
