### ISSUE TITLE
pre-release values get skipped if cargo-release doesn't update the version pre-release

### ISSUE THREAD

**Issue by yaahc** [crate-ci/cargo-release#239]
I noticed this happening whenever I setup a new project using my existing config for cargo-release. I wouldn't switch the version to a dev version prior to release and instead manually bumped the version and ran `cargo release` with no level specified. Doing so prevents `cargo release` from running the pre-release replacements. I've changed my usage to setting `no-dev-version = true` and always runnig `cargo release -- patch` when I need to make a new release. Overall I found the current behaviour to be surprising.

**Comment by epage** [comment]
I could see this going either way.

I believe the intention is that the replacements are associated with the version bump and if there is no version bump, then there are no replacements.  I believe the motivation for this choice in behavior is for it to act as a recovery mode if something goes wrong.

I looked at one of my projects to see how changing this would impact it.  I have my pre-release replacements setup to add new sections to my changelog.  Doing an extra replacement would add superfluous sections, "messing up" the file.  So thinking further about harm/safety, not running replacements means someone could manually adjust do the replacements by hand.  If we run replacements, the user would have no way to opt out without adding even more flags.  This goes along with the "recovery mode" thought.

Not saying "no" (besides, I'm just a contributor), just exploring thoughts on the motivation and impact.

**Comment by yaahc** [comment]
that's fair. I was wondering if you could change the default level from `rc` to `patch`. It seems to be the same in a few use cases and it gives you a very visible message before starting that makes it easy to tell if you should be like "oh wait no, I already changed the version, just publish it, don't increment it again".

**Comment by epage** [comment]
Hadn't noticed that #482 is similar to this issue.

As of #538 which will be released in 0.22, we've changed from
- `cargo release` implies `cargo release release`
- `cargo release release` is used for
  - Removing pre-release versions
  - Recovering from prior failures

To
- `cargo release release` removes pre-release versions
- `cargo release publish`, `cargo release tag`, and `cargo release push` are used for error recovery
- `cargo release` will release the selected crates at their current version

I am also considering adding a `--unpublished` flag to auto-select all crates that have an unpublished version.

I believe #538 takes care of the use case in this issue, so I'm closing this out.  If there is something I missed, let us know and we can re-open
