### ISSUE TITLE
`{{version}}` Should not include version metadata

### ISSUE THREAD

**Issue by Jasper-Bekkers** [crate-ci/cargo-release#308]
Cargo supports having metadata in it's version numbers: https://doc.rust-lang.org/cargo/reference/resolver.html#version-metadata

In the https://github.com/gfx-rs/rspirv/ crate we're using this to specify which upstream SPIR-V headers we're compiling against while keeping our own releases compatible with SemVer. However, cargo dependencies can't contain metadata information.

So for example; a package has version of `0.1.0+1.54` for example, in it's `Cargo.toml` file, the version should still be listed as `0.1.0`.

Right now when we're using `cargo release` we specify the version number like so `cargo release -- 0.1.0+1.54`, however this populates the `{{version}}` regex replacement attribute with `0.1.0+1.54` which isn't valid in a lot of cases. Ideally it should strip everything after the `+` sign and emit that (or alternatively there ought to be a `{{version_no_metadata}}`.

**Comment by epage** [comment]
Thanks fior reporting this! I think having two replacement variables is the way to go, the question just being what to call them

**Comment by Jasper-Bekkers** [comment]
How about `{{version}}` and `{{complete_version}}`?

**Comment by epage** [comment]
Been giving this thought and my suggestions are either
- `{{version}}` (no metadata) and `{{metadata}}` (only metadata)
- `{{version}}` (no metadata) and `{{version_metadata}}` (only metadata)

And users can combine them as they wish

Thoughts?

**Comment by MarijnS95** [comment]
@epage I'd argue that `{{version}}` is commonly used in a position to fill a line in `README`s showcasing what to copy-paste, or to update other crates' dependencies inside the same git repo. Both shouldn't use metadata and I'm all in favour for dropping that from `{{version}}` as you describe, even if not backwards compatible.

For your examples, does the `{{*metadata}}` include or exclude the `+`? That is, to compose the original version back, would users have to write `{{version}}+{{version_metadata}}`?

**Comment by epage** [comment]
I was thinking it would exclude the `+`.  In the case of the OP, this would mean `{{metadata||` would directly map to the version they are tracking which you can't do if you have `+`.  This just requires a little more work to reconstruct but ends up being the most flexible.

**Comment by epage** [comment]
btw I'm  working on another PR that will have shared work with this effort

**Comment by epage** [comment]
Its in

**Comment by Jasper-Bekkers** [comment]
@epage I have to say I'm in favor of your suggestion - like @MarijnS95 said, `{{version}}` is usually used in places where you want users to copy-paste a working version directly into their dependencies list (or update a dependencies list as part of the release process).

If you want I can close my PR in favor of your refactoring.

**Comment by epage** [comment]
My refactoring is in and ready for someone to implement this on top of it.  We now have `pkg.version.full_version` (to get metadata) and `pkg.version.bare_version_string` (no metadata).

**Comment by epage** [comment]
If it'd help, feel free to add a `Version::metadata_string` variable

**Comment by epage** [comment]
Was looking at this again and the annoying thing is we have
- `prev_version`
- `version`
- `next_version`

Each can have its own metadata.  Unsure if I should do similar (`prev_metadata`, `metadata`, `next_metadata`).  Thoughts?
