### ISSUE TITLE
Move cargo-release to crate-ci organization

### ISSUE THREAD

**Issue by sunng87** [crate-ci/cargo-release#311]
These days I can spend little time on cargo-release project. @epage has been working on it for most features and fixes. To welcome more developers, I suggest to transfer this tool to the [crate-ci](https://github.com/crate-ci/) organization. 

Things to check:

- [x] crate.io release permission
- [x] crate.io listing
- [x] urls in docs
- [x] remove donation from README
- [x] adopt conventions of crate-ci, like `CONTRIBUTING.md` if any

**Comment by epage** [comment]
Looks like I at least have the necessary permissions for crates.io so I can modify them as needed later
