### ISSUE TITLE
crates-index feedback

### ISSUE THREAD

**Issue by kornelski** [crate-ci/cargo-release#326]
You're using the crates-index crate. I'm preparing to release 1.0 of the crate, and I'd like to finalize the API. Do you have any feedback or requests regarding the crate?

**Comment by pksunkara** [comment]
Hmm... `cargo-workspaces` is in the same situation. Don't know how different master is.

**Comment by kornelski** [comment]
The differences are in the readme: https://github.com/frewsxcv/rust-crates-index#migration-from-016-and-017
