### ISSUE TITLE
`publish` ignores dirty files that `release` does not

### ISSUE THREAD

**Issue by asomers** [crate-ci/cargo-release#336]
I always create a `target` symlink in each workspace, to store Cargo's generated files on a different file system.  But cargo release warns about it, like this:
```
[2021-09-29T03:21:18Z DEBUG cargo_release::git] Dirty because of:
    target
[2021-09-29T03:21:18Z ERROR cargo_release] Uncommitted changes detected for nix, please commit before release.
```
That forces me to delete the symlink before running `cargo release`, which then causes `cargo publish` to recreate the target directory, but this time as a regular directory instead of a symlink.

Would it be possible to make cargo-release ignore `target` when doing its git dirty check?

**Comment by epage** [comment]
Does `cargo publish` complain about the symlink?

Whats your `.gitignore` look like?

btw have you considered setting `CARGO_TARGET_DIR`?
https://doc.rust-lang.org/cargo/reference/environment-variables.html

**Comment by asomers** [comment]
`CARGO_TARGET_DIR` is close, but not good enough, because it needs to be set individually for each workspace.  The proposed `CARGO_TARGET_DIR_PREFIX` variable would solve the problem completely.
https://github.com/rust-lang/cargo/issues/5544
`cargo publish --dry-run` does not complain about target.  The .gitignore file contains `target/`.  But now that you mention it, the trailing slash might be confusing git.  If I remove that, then `git status` shuts up about target.  Would that stop cargo-release's warning?

**Comment by epage** [comment]
Yes, that should quiet `cargo-release`.

There is still an issue with `cargo publish` and `cargo-release` identifying dirty files in different ways.

**Comment by epage** [comment]
> There is still an issue with cargo publish and cargo-release identifying dirty files in different ways.

Just remembered that we have to be more generous than `cargo publish` because we we modify files not checked by `cargo publish` (lock file, dependent `Cargo.toml`, anything touched by replacements or hooks).

In fact, we need to be more generous than we currently are, so created #391
