### ISSUE TITLE
cargo release --execute times out everytime

### ISSUE THREAD

**Issue by rbtcollins** [crate-ci/cargo-release#339]
E.g. `[2021-10-08T14:03:20Z ERROR cargo_release] Fatal: Timeout waiting for crate to be published.`

What is happening there and how can we get more insight to troubleshoot/fix it?

**Comment by rbtcollins** [comment]
Oh and the crates were https://crates.io/crates/unleash-api-client and https://crates.io/crates/rocket-enumform

**Comment by yamadapc** [comment]
Logs print:
```
[2021-10-30T06:25:41Z DEBUG cargo_release::cargo] Crate index update failed with invalid version 0 on git_proxy_options; class=Invalid (3)
```

Until timeout.

**Comment by yamadapc** [comment]
Upgrading `libgit2` has fixed the issue for me.

```
brew upgrade libgit2
```

**Comment by epage** [comment]
I'll try vendoring libgit2 to see if that helps.
