### ISSUE TITLE
Documentation request: clarify why publish=false packages are released by default

### ISSUE THREAD

**Issue by nicholasbishop** [crate-ci/cargo-release#359]
I'm working my way through trying to release a workspace project. One of the packages is for local dev use only ([xtask](https://github.com/matklad/cargo-xtask) style), so I have `publish = false` set in that package's Cargo.toml. I was surprised to see in the dry run that `cargo release` still wants to update the version and push a tag for that package.

I thought maybe this was a bug, but I found this comment that suggests it's intentional: https://github.com/crate-ci/cargo-release/issues/253#issuecomment-855835877

It seems like a surprising default to me, but I think it would help to at least document why this behavior is desirable. I'm still new to using workspaces so I'm probably just not thinking about some case where it's still helpful to do the version bump even though the publish step is skipped.

**Comment by epage** [comment]
As one example, not all CLIs get published to crates.io but they want a release process.

On another level, I see this as a matter of separation of concerns.  Rather than having one flag that encompasses a lot of policy, we have individual flags to allow people to get the policy they want.

**Comment by nicholasbishop** [comment]
Thanks for the explanation and doc update!
