### ISSUE TITLE
Tag is created before making the bump commit

### ISSUE THREAD

**Issue by voidpumpkin** [crate-ci/cargo-release#365]
Tag is created before making the bump commit, why is that?

Command output:
https://github.com/voidpumpkin/yew/runs/4422995210?check_suite_focus=true#step:7:11

Is this a bug or there is some reason why it works this way?

**Comment by voidpumpkin** [comment]
took me a while to process that you should bump only after releasing

**Comment by epage** [comment]
I'm a bit confused as to what is being shown here.

Is it the ordering of these two lines in the log?

> Pushing yew-v0.19.0 to origin
> Pushing HEAD to origin

That is just the order things are pushed.  If you do a dry-run with `--verbose` (or maybe `-vv`), you'll see when we do the commit and the tag which are done much earlier than the pushes.  I'm not aware of a specific need to the ordering of pushes.

**Comment by voidpumpkin** [comment]
@epage  As i wrote when closing, the issue was me not realizing that you should do bumps only after releasing.

I got confused why tag does not include bump commits.

**Comment by epage** [comment]
Yes, that was part of what isn't clear to me.  By "bump commit", I assume you mean the commit that updates the version number.  The tag should be on that commit.  So what is the bump after release?  Or are you talking about the post-release dev version bump?
