### ISSUE TITLE
Cargo release gives wrong release order if inter-dev crate is optional

### ISSUE THREAD

**Issue by metaclips** [crate-ci/cargo-release#366]
We are currently trying to release our crates at [Ockam](https://github.com/ockam-network/ockam) using cargo-release, publish order seems wrong as dependent crates are not ordered correctly.
This is the release order running `cargo release release --no-tag --no-dev-version --execute`
<img width="429" alt="Screenshot 2021-12-08 at 3 24 32 PM" src="https://user-images.githubusercontent.com/31141573/145224822-f7502ea9-5e6b-4aba-ae52-1f384e482501.png">

ockam_entity depends on [signature_bbs_plus](https://github.com/ockam-network/ockam/blob/a246793db30a1af97ef3af2343fe10f306af2c90/implementations/rust/ockam/ockam_entity/Cargo.toml#L56) but it is released before signature_bbs_plus, which results in the error below
```
 Packaging ockam_entity v0.31.0 (/ockam/ockam/implementations/rust/ockam/ockam_entity)
error: failed to prepare local package for uploading

Caused by:
  failed to select a version for the requirement `signature_bbs_plus = "^0.31.0"`
  candidate versions found which didn't match: 0.30.0, 0.29.0, 0.28.0, ...
```

**Comment by epage** [comment]
Sorry about that, it looks like we overlooked optional dependencies when calculating the release order.  A fix should be released soon,

**Comment by epage** [comment]
v0.18.6 is now released.

**Comment by metaclips** [comment]
🚀 to the stars
