### ISSUE TITLE
Cargo release blocks with Waiting for publish to complete... when using alternative registry

### ISSUE THREAD

**Issue by metaclips** [crate-ci/cargo-release#368]
Using alternative registry [estuary](https://github.com/onelson/estuary), cargo-release blocks while publishing workspace packages. This seems to be due to cargo release searching crates.io as the source of truth if the crate has been updated.

**Comment by epage** [comment]
Yes, we need
- To read the users registry like cargo does
- Support for waiting for registries besides the default

In the mean time, you can [specify the registry in your release.toml](https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md#sources).

**Comment by epage** [comment]
With cargo now blocking, we've instead stopped blocking ourselves.  See #743
