### ISSUE TITLE
Document defaults

### ISSUE THREAD

**Issue by orenbenkiki** [crate-ci/cargo-release#372]
It would be helpful if https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md documented the default values of the various configuration parameters.

**Comment by epage** [comment]
Yes, we should do this.  In addition, #373 adds a `--dump-config` which can both show defaults but also help people debug the results of the layering.

**Comment by epage** [comment]
v0.18.8 is now released with `--dump-config`
