### ISSUE TITLE
Misleading log output for `Pushing ..., ... to origin`

### ISSUE THREAD

**Issue by Nukesor** [crate-ci/cargo-release#403]
First of all, thanks for providing `cargo-release`, it has been a great help!

I'm currently planning to publish a new release and stumbled upon a possible bug while running the dry-run.

The executed command was `cargo release -p pueue`.
The current version as specified in the `Cargo.toml` of the project is `v2.0.0-beta.1`
```
[package]
name = "pueue"
description = "A cli tool for managing long running shell commands."
version = "2.0.0-beta.1"
```

This is reflected in the output log:
```
   Compiling pueue-lib v0.19.0
   Compiling pueue v2.0.0-beta.1 (/home/nuke/repos/tools/pueue/target/package/pueue-2.0.0-beta.1)
    Finished dev [unoptimized + debuginfo] target(s) in 26.66s
   Uploading pueue v2.0.0-beta.1 (/home/nuke/repos/tools/pueue)
warning: aborting upload due to dry run
[2022-01-30T15:06:19Z INFO  cargo_release::release] Pushing development, v2.0.0 to origin
[2022-01-30T15:06:19Z WARN  cargo_release::release] Ran a `dry-run`, re-run with `--execute` if all looked good.
```
However, as you can see, the log says that it'll push a `v2.0.0` ref/tag to `origin` instead of `v2.0.0-beta.1`

I checked whether the same issue appears if one calls the command with the `beta` release identifier:
`cargo release -p pueue beta`

```
   Compiling pueue v2.0.0-beta.1 (/home/nuke/repos/tools/pueue/target/package/pueue-2.0.0-beta.1)
    Finished dev [unoptimized + debuginfo] target(s) in 27.82s
   Uploading pueue v2.0.0-beta.1 (/home/nuke/repos/tools/pueue)
warning: aborting upload due to dry run
[2022-01-30T15:07:28Z INFO  cargo_release::release] Pushing development, v2.0.0-beta.2 to origin
[2022-01-30T15:07:28Z WARN  cargo_release::release] Ran a `dry-run`, re-run with `--execute` if all looked good.
```

This however also seems to behave kind of weird, as the logs tell us that `v2.0.0-beta.1` will be uploaded and a tag for `v2.0.0-beta.2` will be pushed to `origin`.

Maybe I'm misunderstanding something, but that log output definitely had me worried and I didn't dare to publish the release yet :D

Best regards

**Comment by Nukesor** [comment]
Nevermind, I just read in your docs, that on a raw `release` any pre-release extensions will be removed.
This explains the behavior of both cases.

I think I got confused by the formatting of the `Pushing ..` line. My assumption was that this was a list of refs that're going to be pushed to origin.
But I guess that this is just the info that a new commit that bumps the version to the next version will be pushed to the specified branch?

**Comment by Nukesor** [comment]
While going through the release log of the `pueue-lib` create I found another weird thing.

Over there, the version was set to `v0.19.0` in the `Cargo.toml` and the release was published via a simple `cargo release -p pueue-lib`

The log output looks like this: (This is the log of the non-dry release run)
```
   Compiling tokio-rustls v0.23.2
   Compiling pueue-lib v0.19.0 (/home/nuke/repos/tools/pueue/target/package/pueue-lib-0.19.0)
    Finished dev [unoptimized + debuginfo] target(s) in 14.55s
   Uploading pueue-lib v0.19.0 (/home/nuke/repos/tools/pueue/lib)
[2022-01-30T14:37:29Z INFO  cargo_release::cargo] Waiting for publish to complete...
[2022-01-30T14:37:32Z INFO  cargo_release::release] Pushing development, pueue-lib-v0.19.0 to origin
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 182 bytes | 182.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:Nukesor/pueue
 * [new tag]         pueue-lib-v0.19.0 -> pueue-lib-v0.19.0
```

This log tells us that `pueue-lib-v0.19.0` is pushed to origin, which looks suspiciously like the tag, that's pushed shortly afterwards.

I'm now confused once more, whether the log output is for the bumping commit or the push of the actual commit tag.

**Comment by epage** [comment]
In case it wasn't clear, when you do a dry-run release, we are calling `cargo publish --dry-run` on your code as-is which means it will report the existing version and not the bumped version.

>  I got confused by the formatting of the Pushing ..., ... to origin line. My assumption was that this was a list of refs that're going to be pushed to origin.
> But I guess that this is just the info that a new commit that bumps the version inside the Cargo.toml/lock will be pushed to the specified branch?

We are pushing "development" branch and "v2.0.0-beta.2" tag to origin.  The log is correct as-is.

> This log tells us that pueue-lib-v0.19.0 is pushed to origin, which looks suspiciously like the tag that's pushed shortly afterwards.

Let's break down the log into its individual parts
```
[2022-01-30T14:37:32Z INFO  cargo_release::release] Pushing development, pueue-lib-v0.19.0 to origin
```
This is log output from `cargo-release` describing what its about to do ("pushing" rather than "pushed")
```
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 182 bytes | 182.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:Nukesor/pueue
 * [new tag]         pueue-lib-v0.19.0 -> pueue-lib-v0.19.0
```
This is output from `git push` which summarizes at the end what it did do

**Comment by Nukesor** [comment]
Hm, I assume it's not easy to do a `cargo publish --dry-run` with the bumped version?
I guess one would have to create a temporary commit for the version-bump, that'll be reverted once the dry-run is done.
I see how this could lead to some weird behavior or broken intermediate states, if the user decides to abort a `cargo release --dry-run`.

It may be a good idea to document this behavior though, as I couldn't find more info about this in the `--dry-run` help or the [Cargo-release reference](https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md).

Anyhow, this is definitely what confused me, as I checked whether the correct verisons will be uploaded and pushed to the remote. Sorry for bothering you.

If you're fine with a few documentation updates, I'll create a PR that documents this behavior :)
