### ISSUE TITLE
Docs refers to unexisting CLI option `--metadata`

### ISSUE THREAD

**Issue by MicroJoe** [crate-ci/cargo-release#414]
On the [latest documentation page](https://github.com/crate-ci/cargo-release/blob/71733f2666659be7c0e9312fe1c92004f56d5bd0/docs/reference.md), the `--metadata` long option is listed in the CLI arguments table. However, this option is not available in the latest `0.20.0` release CLI:

```console
$ cargo release --metadata      
error: Found argument '--metadata' which wasn't expected, or isn't valid in this context

	If you tried to supply `--metadata` as a value rather than a flag, use `-- --metadata`

USAGE:
    cargo release [OPTIONS] [LEVEL_OR_VERSION]

For more information try --help

$ cargo release --version                                    
cargo-release 0.20.0
```

However, one can see a similar option available in the `--help`, but only in the short form with `-m`:

```console
$ cargo release --help | nl | grep metadata -C 1 
    21	    -m <METADATA>
    22	            Semver metadata
```

**Comment by epage** [comment]
Thanks for reporting this!  Its resolved in v0.20.1
