### ISSUE TITLE
cargo-release incorrectly detects local changes if there's a file named `head` in root dir

### ISSUE THREAD

**Issue by jbr** [crate-ci/cargo-release#430]
In order to check for dirty files, cargo-release runs `git diff HEAD --exit-code --name-only`, checks the exit code, and splits the standard out. However, when there's a file named `head` in crate or workspace root, git fails with an exit code of `128` but no stdout output.  On stderr, it echoes this:

```bash
$ git diff HEAD --exit-code --name-only
fatal: ambiguous argument 'HEAD': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

This then fails with the confusing verbose log:
```
[… DEBUG cargo_release::git] Dirty because of:

[… ERROR cargo_release::release] Uncommitted changes detected, please commit before release.
```
with no further information other than a blank line between those messages.

I'll throw together a quick PR with `--`, fixing this

**Comment by epage** [comment]
Thanks for reporting this!

**Comment by epage** [comment]
v0.20.3 is now released with the fix for this
