### ISSUE TITLE
Unable to release an alpha version of a crate

### ISSUE THREAD

**Issue by JasonShin** [crate-ci/cargo-release#481]
Hi,

I'm trying to release an alpha version of a Crate that I'm working on https://github.com/JasonShin/sqlx-ts/.

I've set up a Github action CI step https://github.com/JasonShin/sqlx-ts/blob/main/.github/workflows/release.yaml#L135 like in the link. However, it seems like I cannot release an alpha version using `cargo-release`, it's throwing an error in the CI saying that the crate version 0.1.0 is already released (I yanked the version already in crates.io).

```
cargo release \
              --tag-name="$version" \
              --dev-version-ext="$dev_prefix" \
              --no-tag \
              --execute \
              --no-confirm
```

This is the command that I'm using to try and release the alpha version, which isn't working as described above

**Comment by epage** [comment]
A positional argument is expected to say what the released version will be but none was provided.  The default is to release the current version as-is.

And to clarify, what we call "dev-version" is the post-release version or what version will be used for development after the release.
