### ISSUE TITLE
Use as library

### ISSUE THREAD

**Issue by 7596ff** [crate-ci/cargo-release#492]
I have a complicated workflow, and I plan to use multiple tools to achieve my desired result, as no one tool will do the job. I could call out to a shell in a rust program, execute cargo-release, and parse its output, but it'd be cool to call it as a function instead with, for example, a list of the tags it creates, so that further post-processing can create GitHub releases from those tags and post those release notes to a Discord channel.

Of course if there's a better way to achieve this, I'm all ears, but I'm interested to see if this is a viable request.

**Comment by epage** [comment]
`cargo-edit` has `cargo-set-version`.  What else might be needed from a library of `cargo-release` as compared to just writing the logic you need yourself?

`cargo-release` has a lot of policy baked in that make it not very conducive to exposing as a library for people to provide their own policy.

**Comment by 7596ff** [comment]
Thanks, that sounds just fine.
