### ISSUE TITLE
`consolidate-commits` doesn't seem to consolidate the commits

### ISSUE THREAD

**Issue by max-sixty** [crate-ci/cargo-release#495]
Thanks a lot for the excellent tool! We're hoping to use it for PRQL.

Taking this commit in prql/prql: https://github.com/prql/prql/commit/3127acdae461851289077e37a5643f6ce4398723 (from [PR](https://github.com/prql/prql/pull/795) and running:

```
 cargo release --no-push --no-publish --no-verify -x --no-confirm minor
```

creates four commits:

```
* a3ad2f1a - (HEAD -> release, tag: 0.3.0) (cargo-release) version 0.3.0 (47 seconds ago) <Maximilian Roos>
* 4f20fdb2 - (cargo-release) version 0.3.0 (48 seconds ago) <Maximilian Roos>
* 5364c5e6 - (cargo-release) version 0.3.0 (48 seconds ago) <Maximilian Roos>
* f71c67d9 - (cargo-release) version 0.3.0 (48 seconds ago) <Maximilian Roos>
* b6b76ec9 - (cargo-release) version 0.3.0 (49 seconds ago) <Maximilian Roos>
* 10abccce -  (2 minutes ago) <Maximilian Roos>
* 3127acda - (origin/main, origin/HEAD, main) Prepare to use `cargo release` for releases (#795) (2 minutes ago) <Maximilian Roos>
```

...but yet there's a `consolidate-commits = true`: https://github.com/prql/prql/commit/3127acdae461851289077e37a5643f6ce4398723#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R19. 

Is this intentional? Or am I doing something wrong? 

For context, the other crates are all bindings for the main crate, so we want to bump them, but not publish them. I was hoping to:
- Bump all the crates
- Have a single commit
- With a single tag (which works)

**Comment by epage** [comment]
Looks like we had a bug when layering a package's config on top of the workspace's config.   While we need to get tests for this, the fix here is obvious so I'm prioritizing getting the fix out now.

**Comment by epage** [comment]
v0.21.1 is now released

**Comment by max-sixty** [comment]
Thanks @epage !
