### ISSUE TITLE
Push or not push (confusion with param)

### ISSUE THREAD

**Issue by sergio-ivanuzzo** [crate-ci/cargo-release#498]
Hi ! First of all thanks for cool crate. I have an issue about push param. From its documentation it's a bit confusion what this param actually do: allow push or deny ?

<html>
<body>

push | --no-push | bool | true | Don't do git push
-- | -- | -- | -- | --

</body>
</html>

maybe better to rename it ? Something like allow-push (--allow-push) ?

**Comment by epage** [comment]
The config field is `push` and can be set to true/false

Since the default is to push, the flag is `--no-push` to override that default (though there is a hidden `--push` in case you change it in your config but want to override it)
