### ISSUE TITLE
Fatal: IO Error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by botika** [crate-ci/cargo-release#500]
I try it in https://github.com/botika/v_escape but returns:

```
[2022-07-27T16:25:33Z INFO  cargo_release::release] Update v_escape_codegen to version 0.1.3
[2022-07-27T16:25:33Z ERROR cargo_release] Fatal: IO Error: No such file or directory (os error 2)
```

**Comment by epage** [comment]
If you run with extra verbosity (`-vv`), it'll most likely point to what the root cause is.

From my quick glance, my guess is that `/release.toml` applies to the whole workspace and `pre-release-hook` is relative to the current crate being released, so it can't find `/v_htmlescape/hook.sh`, etc.

**Comment by botika** [comment]
I remove it. I close. thanks
