### ISSUE TITLE
Various issues with clap's --help output formatting

### ISSUE THREAD

**Issue by pacak** [crate-ci/cargo-release#510]
Trying to adopt cargo-relese and running into some issues: cargo release --help produces several pages of output even if the terminal window is expanded to the full size (eyesight issues) which makes it mildly annoying to use: constant scrolling and memorizing, plus the green color is (more eyesight issues) is harder to read than the gray text - I believe `DisableColoredHelp` fixes this issue.

I was able to change the formatting a bit by hands to make it fit just on a single page within 100 columns.

I tried to raise this issue with clap directly (same problem but a different binary), but it was closed.
https://github.com/clap-rs/clap/issues/3780

> We offer control over both for application authors. I'd also recommend reaching out to them if you have concerns over how their applications are configured.

**Comment by epage** [comment]
Unfortunately in this case, you've reached out to an application author who prefers the current colored help to nothing though I do think it can stand to be improved, see https://github.com/clap-rs/clap/issues/2963
