### ISSUE TITLE
How to ignore dependencies using branch

### ISSUE THREAD

**Issue by rakanalh** [crate-ci/cargo-release#519]
Hello,

How would i get cargo-release to ignore a third-party package which i am pulling using a specific branch?

As such:
```
sp-core-hashing = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.28" }
```

I am seeing:
```
error: all dependencies must have a version specified when publishing.
dependency `sp-core-hashing` does not specify a version
Note: The published dependency will use the version from crates.io,
the `git` specification will be removed from the dependency declaration.
```

**Comment by epage** [comment]
This isn't a cargo-release error but a cargo-publish error.

Cargo requires all published packages to only rely on other published packages.  A git-only dependency precludes that.

If you'd like to continue this discussion, I'd recommend doing so on the cargo issue tracker.
