### ISSUE TITLE
Provide crate as library and command line

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [crate-ci/cargo-release#535]
Is it possible to expose this project as a simple library.  
Based on that it can be possible to integrate into a server command to perform releases.

**Comment by epage** [comment]
Does #536 provide what you need?

**Comment by epage** [comment]
Going to go ahead and close this as we are unlikely to do anything more than what is in master

**Comment by MarcAntoine-Arnaud** [comment]
Awesome I'll test it next week
