### ISSUE TITLE
pre-release-commit-message template replacements don't seem to work

### ISSUE THREAD

**Issue by sunshowers** [crate-ci/cargo-release#540]
Hi there!

I'm trying to adapt cargo-release to work for nextest. The nextest workspace consists of several crates, each with their own independent versioning.

If I'd like to update one of nextest's crates, I'd like to be able to do:

```
cargo release -p nextest-filtering 0.2.2 --execute
```

and have a commit be created with the requisite version bumps and the message:

```
[nextest-filtering] version 0.2.2
```

and a signed tag created on this commit called `nextest-filtering-0.2.2` with message:

```
nextest-filtering version 0.2.2
```

Here's my first attempt at configuring that, based on [the reference](https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md#placeholders):

https://github.com/nextest-rs/nextest/blob/main/release.toml

However, when I run:

```
cargo release -p nextest-filtering 0.2.2 --execute
```

the commit that gets created is:

```
commit 49aaac68f9fae149b957ed79508e3551cd20d816 (HEAD -> main)
Author: Rain <rain@sunshowers.io>
Date:   Fri Oct 14 12:23:50 2022 -0700

    [{{crate_name}} version {{version}}
```

which indicates that template replacements aren't working.

Any idea how to make them work?

```
% cargo release --version
cargo-release 0.21.4
```

**Comment by epage** [comment]
> consolidate-commits = true

This tells `cargo-release` to use a single commit for all version bumps which means there is not a specific crate name or version to use in case you run `cargo release --workspace` or `cargo release -p one -p two` (and we don't want it conditioned on how you run as that might cause problems).

Setting this back to `false` should get you exactly the behavior you want.

Note: in the next version, I'm looking at making `consolidate-commits = true` the default which is why I suggested still explicitly setting it.  The focus on the next release is to better scale up with large workspaces.

**Comment by sunshowers** [comment]
Got it, thanks! Just managed to debug this myself as well.

**Comment by sunshowers** [comment]
BTW I did a writeup of how nextest uses cargo-release: https://github.com/nextest-rs/nextest/blob/main/internal-docs/releasing.md

**Comment by epage** [comment]
> For each changed crate, in topological order (internal dependencies like nextest-filtering first, cargo-nextest last), run cargo release -p <crate-name> <version>. For example, cargo release -p nextest-runner 0.28.0. This will perform a dry run.

In the upcoming version of `cargo-release`, my hope is that this will change to
- In "Prepare releases", people run `cargo release version -p <crate> <version> -x`
- In "Create and push tags", people run `cargo release`

This is part of an effort to support two-phase release (#119) which I hope will help with auto-release (#117) and alternative workflows (#528)

> PUBLISH_GRACE_SLEEP=5 

Please don't tell me you ran into issues with this.  It **should** be waiting for you though I'm looking forward to https://github.com/rust-lang/cargo/pull/11062 being merged

**Comment by sunshowers** [comment]
Ooh that looks really good as a way to do things. How would that distinguish between when to tag + push and when to publish crates?

Ah, I didn't realize cargo release already waited a bit. This is a replacement for a very simple script I had locally that slept for 5 seconds in between publishes.

**Comment by sunshowers** [comment]
Oh never mind, misread that! You were talking about steps I and II.

**Comment by epage** [comment]
Also, you might be able to replace `release-publish.toml` with `cargo release publish --publish`

`--publish` is telling the `cargo release publish` command to override the config and do a publish anyways.  Its not a `--force` because I kept the flags the same between `cargo release` and the step subcommands.

**Comment by sunshowers** [comment]
Thanks @epage! Looks like it does work and simplifies things tremendously.

**Comment by epage** [comment]
I've updated the documentation on this.  I've also added #604 and am reconsidering #116, including erroring when a variable is present.

**Comment by MarijnS95** [comment]
@epage thanks for updating that, just curious why this user error is almost invisible behind `debug!` logs.

Furthermore, now that `dev-version=true` support is gone, what is there to be split/consolidated about commits? And what makes it impossible to have the to-be-released version in the pre release commit?

**Comment by epage** [comment]
`consolidate-commits` did not deal with dev-version but consolidating commits between workspace members.  When releasing more than one crate, they might be using different versions, so we have no version to put in the replacement.  When you tell cargo-release they are using the same version, we do support the version in replacements.

`consolidate-commits` should only be defaulted to true in a workspace so this shouldn't affect single-crate cases.

**Comment by MarijnS95** [comment]
Ah right, the crate I had this problem with "is a single crate", but has workspace members for examples (which could have just been regular `examples/...rs` files). Thanks, now I at least know what to write when setting this back to `true` :)

But that also means there's no per-crate version for releasing multi-crate workspaces with one release per commit?

**Comment by epage** [comment]
Could you re-frame that question., I'm not quite sure what you are asking.

**Comment by MarijnS95** [comment]
I may have simply misunderstood while writing that: when in a workspace, and `consolidate-commits = false`, `{{version}}` automatically becomes available again. No question to be asked, just me getting lost in the options - apologies for the noise.

All that remains is finding a more user-friendly system for filling in or rejecting `{{version}}` with the default of `consolidate-commits = true`, _before_ pushing out the borked commit to git.
