### ISSUE TITLE
`post-release-replacements` no longer functional?

### ISSUE THREAD

**Issue by aschampion** [crate-ci/cargo-release#599]
Firstly, thanks for the useful tool.

My crates are configured with `publish = false`, because I want CI to upload to crates.io (triggered by the tags from cargo-release). I used `post-release-replacements` to add unreleased sections to the changelog and other new dev preparation following the release commit/tag. Previously this worked fine when `--dev-version` was also passed, but since that's been removed I haven't been able to make a post-release commit work. I don't miss dev versions, but still would like to automate a commit with post-release replacements.

Looking at the code, I don't even see where `post-release-replacements` is used anymore. Is there something I'm missing, or are post-release commits/replacement no longer possible?

**Comment by epage** [comment]
We removed post-release dev version in #553 which included post-release-replacements, though we forgot to remove the config fields.

> I don't miss dev versions, but still would like to automate a commit with post-release replacements.

What post-release replacements do you want to do that are unrelated to a dev version?  In planning and supporting features, it helps a lot to understand what people are trying to accomplish.

**Comment by aschampion** [comment]
Ah, good to know the fields should be removed. I don't mind that they're gone, was just confused if there was still some way to use them.

> What post-release replacements do you want to do that are unrelated to a dev version?

Mostly just setting up unreleased sections in changelogs and other docs. I avoid prerelease versions only because of cargo's explicit matching policy for them, which can make tracking intended semver dependencies between crates a hassle. But that's definitely a fringe issue.

My use case is trivially fulfilled by a little shell sed script instead, I just wanted to be sure I wasn't misunderstanding something with the dev-version removal or `publish = false` vs `release = true`, etc.

**Comment by epage** [comment]
Feel free to check out [what I do for changelogs](https://github.com/crate-ci/cargo-release/blob/master/Cargo.toml#L21).  Worked well for me for all of my projects though I am tempted to try out cargo-changelog
