### ISSUE TITLE
Replacements with workspace versioning?

### ISSUE THREAD

**Issue by max-sixty** [crate-ci/cargo-release#602]
I know this is one of many issues that I've put in — thank you in advance, I feel like PRQL has got more help than we deserve!

As per the recent issues, we've moved to workspace versioning, which has worked quite well.

But we had a text replacement in one package which doesn't seem to work any longer. Neither the original, at the crate level, nor the proposed code in https://github.com/prql/prql/pull/1162, at the workspace level, works with `cargo release version patch -vv -x`

(also FYI the "See [release.toml](https://github.com/crate-ci/cargo-release/blob/master/release.toml) for example." in the replacements section https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md now doesn't contain any replacements.)

Ofc it's possible that I missed something... Thanks again!

**Comment by epage** [comment]
Thanks for pointing out the bad link; its now fixed.

As for the issue, I wasn't able to reproduce it
```console
prql/prql-js $ cargo release major -vv
...
   Replacing in ../playground/package-lock.json
--- ../playground/package-lock.json     original
+++ ../playground/package-lock.json     replaced
@@ -29 +29 @@
-      "version": "0.2.11",
+      "version": "1.0.0",

   Replacing in package.json
--- package.json        original
+++ package.json        replaced
@@ -22 +22 @@
-  "version": "0.2.11"
+  "version": "1.0.0"
...
```

Was I doing anything different than you?  This was running cargo-release out of master but that should match the latest release.

**Comment by max-sixty** [comment]
This was my misunderstanding! `cargo release version patch -vv -x` indeed doesn't do the replacement. But that's intended — if followed up with `cargo release replace -vv -x`, it does do the replacement.

---

FWIW I do like the new split of commands; it feels safer to see the impact of some smaller command — like changing versions or replacing — without worrying about whether it's going to push / publish. `-x` is great, but sometimes I _do_ want to do things like a replacement / tag, but definitely don't want to publish a crate[^1].

[^1]: Maybe there's some concept of `-x` and `-X`, where the former can mutate something locally and the latter can mutate the destination. Or maybe it's just on the user to think about what they're doing :)
