### ISSUE TITLE
Add option to disable signing

### ISSUE THREAD

**Issue by fschutt** [crate-ci/cargo-release#629]
For some reason, running `cargo release` with `sign-commit = true` in the release.toml always fails with

```

error: gpg failed to sign the data
error: unable to sign the tag
```

I can't delete the lines from the release.toml since it works fine for other team members. `gpg` is installed properly on my Macbook:

```
$ gpg --version
gpg (GnuPG) 2.3.8
libgcrypt 1.10.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/fs/.gnupg
Unterstützte Verfahren:
Öff. Schlüssel: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Verschlü.: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
           CAMELLIA128, CAMELLIA192, CAMELLIA256
AEAD: EAX, OCB
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
```

I want to be able to override this setting with something like `--disable-signing` or `--disable-gpg` to publish without having to modify the release.toml (since that would mean I would have to undo the change after the release again).

**Comment by epage** [comment]
For every one of the `--flag` there is a hidden `--no-flag`, so this would be `--no-sign` in your case.

Granted, I'm assuming if your team has it set to sign, they would prefer you to sign as well.
