### ISSUE TITLE
Proposal: bring back `post-release-replacements`

### ISSUE THREAD

**Issue by danielparks** [crate-ci/cargo-release#630]
I’m automating my release process and there are a few steps that cargo-release doesn’t support. One of them is updating the change log _after_ the release with a new “Unreleased” section. (I would prefer not to have that section in the release itself.)

`post-release-replacements` would be perfect for my use case. It’s actually the same use case that was described when it was added in PR #228.

It was removed in PR #553 along with `dev-version`, but I think most of the problems there were actually with `dev-version` and the default behavior. Re-adding `post-release-replacements` wouldn’t introduce any new default behavior, so I suspect it won’t suffer from the same problems.

I’d be happy to submit a PR.

I‘m unsure if it’s worth making it work nicely with `--unpublished`(#551), but I’d be happy to take a crack at that.

Alternatively, the [“{Pre,Post}-release Replacements” heading in reference.md](https://github.com/crate-ci/cargo-release/blob/d4dc17997434b55e73520c4f03abaaf9c6d0f72c/docs/reference.md#prepost-release-replacements) should be updated. (Again, happy to submit a PR.)

Older issue: #599.

**Comment by epage** [comment]
I'd like to see a more solid use case than this as this feature can make it so there is always a change after a release, breaking change detection. I do not want to add "but ignore these changes" support. I also feel covering footguns with documentation is a non-solution as it will most likely be missed.

As for PRs to clean up stale docs, sure!

**Comment by danielparks** [comment]
The only other usage I can imagine off-hand is updating links to binary packages or some other release product, but absent somebody actually wanting to do that, it doesn’t seem worth it.

PR #632 submitted.
