### ISSUE TITLE
Feature request: date-versioned releases?

### ISSUE THREAD

**Issue by woodruffw** [crate-ci/cargo-release#631]
First of all, thanks for `cargo release`! It's a fantastic tool, and it's my preferred way to orchestrate releases of my Rust projects.

Date-versioning (`vYYYY.MM.DD` for year, month, and date) is a versioning paradigm, popular with libraries that have stable APIs but regularly perform updates to provide newer copies of vendored data. Examples include certificate trust stores and codegen'd libraries from revolving data sources.

It would be nice if `cargo release` had support for bumping the version in accordance with date versioning rules. This could take the form of `cargo release date`, similar to the current CLI for "normal" versions (like `cargo release major`). 

If there's interest in this feature, I'd be happy to try and add support for it! Otherwise, thanks again, and feel free to close if you feel it's out of scope for this tool.

**Comment by epage** [comment]
Do you have an example of this being used in a mainstream crate?

While people might view the API as stable and that `dep = "*"` is fine, crates.io will block that dependent from being published and cargo won't unify the versions, leading to bloat.

To work within the rust ecosystem, it seems like it'll need to be paired up with semver, like `1.YYYY.MM` and hope once a month is good enough.

**Comment by woodruffw** [comment]
Hmm, nothing mainstream in Rust -- I use it for some PyPI packages (where it's widely supported by the ecosystem) and I'd like to use it for [usb-ids.rs](https://github.com/woodruffw/usb-ids.rs), but you've raised a great point about the resolution.

I also think you're right about that pairing with SemVer -- you could use "post" releases to do cadences within a month (`1.YYYY.MM.postN`), but I'm not sure if Cargo actually guarantees an ordering/resolution preference for the latest postrelease. Alternatively it could be `1.YYYY.MMDD`, but that's not quite as readable. 

Given that neither is close to the date versioning convention in other ecosystems, it probably doesn't make sense for `cargo release` to impose a new convention here. I'll close this out until I have a better sense of what this should look like 🙂

**Comment by epage** [comment]
[semver](https://semver.org/) does not recognize post-release, only pre-release unfortunately.
