### ISSUE TITLE
Exclude folders from packaging

### ISSUE THREAD

**Issue by kekonn** [crate-ci/cargo-release#642]
Sorry if I'm missing something obvious, but I'm looking for someting like a .gitignore file for the packaging step. 

Is there such a functionality?

**Comment by epage** [comment]
I assume what you are looking for is https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields

**Comment by kekonn** [comment]
Looks like it. Thanks for helping out this novice Rustacean
