### ISSUE TITLE
`include_bytes!` does not compile.

### ISSUE THREAD

**Issue by AntoniosBarotsis** [crate-ci/cargo-release#643]
I have a crate that uses `include_bytes!` to assign a byte array to a variable. The crate builds fine both on debug and release.

When I run `cargo release` however, I get a `The system cannot find the path specified.` error. I'm sort of guessing that you create a folder somewhere, copy the files there and compile them, is it possible to include the file manually somehow?

**Comment by epage** [comment]
We aren't doping any temp folders.  What `cargo publish` does is a `cargo package` and then builds what was built to ensure your crate is complete.  I'd recommend trying to reproduce with `cargo package`.  Most likely what is happening is the included file isn't marked for inclusion.  You can verify this with `cargo package --list`.  The [exclude and include](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields) fields control this.

**Comment by AntoniosBarotsis** [comment]
Thanks for the quick reply!

`cargo package` is indeed also failing, although I'm having issues including the file for some reason


```toml
[package]
# ...
include = [ "src", "../assets/logo.png"]
```

I feel like this should work but the logo does not get included. 

This isn't really an issue for this repository, if you have an idea of why this might not be working let me know otherwise just close the issue. Thanks again!

**Comment by epage** [comment]
All files must be within the package root. In some specific cases, cargo will move the file into the package root, like license files. It wouldn't work to use `include_bytes` and have cargo change the path needed to access the file.

**Comment by AntoniosBarotsis** [comment]
For anyone curious, see [related](https://users.rust-lang.org/t/including-files-from-parent-directory-in-package/88969/4).
