### ISSUE TITLE
Listing crates to publish that don't publish

### ISSUE THREAD

**Issue by max-sixty** [crate-ci/cargo-release#644]
This is minor — the only issue is the listing rather than any actual action.

Here, only three of these will get published, because the others have `publish=false`, but they're all listed.

```
❯ cargo release publish -x
warning: push target `origin/release` doesn't exist
Publish
  prql-compiler 0.5.0
  compile-files 0.5.0
  prql-compiler-macros 0.5.0
  prqlc 0.5.0
  prql-java 0.5.0
  prql-lib 0.5.0
  prql-js 0.5.0
  prql-python 0.5.0
  mdbook-prql 0.5.0
  prql 0.5.0
? [y/N]
y
```

Thank you!

**Comment by gautamprikshit1** [comment]
I have found the root cause of the problem but having issues with the implementation.

**Comment by epage** [comment]
Sorry, I skimmed over this due to the title. 

Could you provide full reproduction steps and include the output with `-v` or `-vv`?

**Comment by epage** [comment]
As I'm not able to reproduce this locally and without reproduction steps, there isn't anything more we can do on this.

**Comment by max-sixty** [comment]
Sorry for missing the message above @epage. I just tried to repro and couldn't, so I think this is no longer an issue. Thank you!
