### ISSUE TITLE
Release replacements entry is deleted

### ISSUE THREAD

**Issue by max-sixty** [crate-ci/cargo-release#653]
This seems like it's probably user-error, but I can't work it out.

Here's the repro:
- Check out https://github.com/PRQL/prql/commit/31ec987606c057ff774cf5f1876bf2ba9a57bc65
- Run `cargo release version patch -x`
- `git diff -- prql-compiler/Cargo.toml` shows one of the pre-release replacements entries deleted:

```diff
diff --git a/prql-compiler/Cargo.toml b/prql-compiler/Cargo.toml
index b28ada5..47e47bc 100644
--- a/prql-compiler/Cargo.toml
+++ b/prql-compiler/Cargo.toml
@@ -56,11 +56,3 @@ duckdb = {version = "0.7.0", features = ["bundled", "chrono"]}
 [[bench]]
 harness = false
 name = "bench"
-
-# Putting this in the workspace root causes it to refer to the path relative
-# to `prql-compiler`? We can place it there when that's fixed.
-[[package.metadata.release.pre-release-replacements]]
-exactly = 1
-file = "../book/src/language-features/target.md"
-replace = 'prql version:"{{version}}"'
-search = 'prql version:"[\d.]+"'
```

(FWIW the comment is old and should actually be removed... but not the whole block!)

Any ideas?

**Comment by epage** [comment]
This seems to be a bug in `toml_edit`, just loading and writing the file causes that section to disappear.

**Comment by epage** [comment]
Minimum reproduction case:
```toml
[package]
metadata.msrv = "1.65.0"

[[package.metadata.release.pre-release-replacements]]
```

**Comment by epage** [comment]
v0.24.6 is released

**Comment by max-sixty** [comment]
Thanks a lot @epage !
