### ISSUE TITLE
TOML corruption

### ISSUE THREAD

**Issue by max-sixty** [crate-ci/cargo-release#663]
Running `cargo release version minor -x` on https://github.com/PRQL/prql/tree/c355785f84ed3dc1d3331d8a2ed03ef3a0fee5ca

Causes this error:

```
error: TOML parse error at line 70, column 10
   |
70 | [[package.
   |          ^
invalid table header
expected `.`, `]]`
```

and leaves lots of these diffs:

```diff

-[[package.metadata.release.pre-release-replacements]]
+[[package.
+metadata.release.pre-release-replacements]]
 exactly = 1
 file = "../.github/workflows/test-rust.yaml"
 replace = 'prefix-key: {{version}}'
 search = 'prefix-key: [\d.]+'
```

**Comment by epage** [comment]
For some reason I was unable to reproduce this.

What version of `cargo-release` did you use?  Did you get it through `cargo install` and, if so, did you use `--locked`?  Any narrower reproduction steps?

btw with the commit you pointed to, I needed to apply this diff
```
diff --git c/prql-compiler/Cargo.toml w/prql-compiler/Cargo.toml
index 257a35a4..455505d4 100644
--- c/prql-compiler/Cargo.toml
+++ w/prql-compiler/Cargo.toml
@@ -90,7 +90,7 @@ search = 'prefix-key: [\d.]+'

 [[package.metadata.release.pre-release-replacements]]
 exactly = 1
-file = "../github/actions/time-compilation/action.yaml"
+file = "../.github/actions/time-compilation/action.yaml"
 replace = 'prefix-key: {{version}}'
 search = 'prefix-key: [\d.]+'
```

**Comment by max-sixty** [comment]
Oh, that's surprising. I'm running with `cargo install cargo-release --locked` (I just uninstalled and reinstalled to confirm). I'm on 0.24.8, MacOS.

FWIW I have got this a few times in the past few weeks.

---

Thanks, yes, I noticed that! It's fixed by the latest `main`, e.g. at `3c701c2b948610b23dd5f1b3cf9597303e4963ec`

---

That said, if you can't reproduce; I can see if it abates, and it's no great stress in the meantime... Fine to close.

**Comment by epage** [comment]
Oh right, I'm running at `HEAD`.   Looks like there was a `toml_edit` release that I'm using locally that *checks notes* fixes newlines in table headers.

v0.24.9 should hopefully fix this for you.

**Comment by max-sixty** [comment]
Excellent! Thanks
