### ISSUE TITLE
Allow local unstaged changes

### ISSUE THREAD

**Issue by fredrik-jansson-se** [crate-ci/cargo-release#677]
I have a number of files and directories, that are not in git and shouldn't be there. Now I can't release anymore:
```
cargo release --execute
error: uncommitted changes detected, please resolve before release:
  cliff.toml (WT_NEW)
  reqwest/ (WT_NEW)
  rustls/ (WT_NEW)
  src/.lib.rs.rustfmt (WT_NEW)
  tokio-tungstenite/ (WT_NEW)
```
```
git status
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        cliff.toml
        reqwest/
        rustls/
        src/.lib.rs.rustfmt
        tokio-tungstenite/

nothing added to commit but untracked files present (use "git add" to track)
```

IMO, these should be ignored.

**Comment by epage** [comment]
Is there a reason these should not be committed **and** not ignored?

**Comment by fredrik-jansson-se** [comment]
Hey, great question! 

I find that working on a library over a longer time, I tend to have a few local scripts (junk) that I use in the development. Some are there for a few days, some tend to have longer life times... 

I could of course ignore them, but that tends to be extra maintenance of the ignore file. So it'd be nice if cargo release wouldn't pay attention to those (warnings are great though, the same way git warns).

All that said, cargo release is a GREAT tool, but with this feature it stands in my way :)

**Comment by epage** [comment]
One option is to use your personal ignore file and have a pattern to them (prefix, directory) to make it more self-managing.

I am just hesitant about removing this safety check but the negative impact it can have on others while those blocked by it have workarounds.  As such I'm going to close this out.

**Comment by fredrik-jansson-se** [comment]
Hey, thanks for getting back to me! While I obviously would have liked to have a flag to get around this behavior, I respect your standpoint!

Thanks again for cargo release, it's an awesome tool!
