### ISSUE TITLE
Error when using with CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse

### ISSUE THREAD

**Issue by ChriFo** [crate-ci/cargo-release#679]
When enabling the [_new index protocol_](https://blog.rust-lang.org/inside-rust/2023/01/30/cargo-sparse-protocol.html) with e.g. the env variable `CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse` I get the following error when running `cargo release patch`:

```
$ cargo release patch
error: The repo at path /usr/local/cargo/registry/index/github.com-1ecc6299db9ec823 is unusable due to having an invalid HEAD reference: reference 'refs/heads/main' not found; class=Reference (4); code=NotFound (-3)
```

There is no `github.com-*` folder but a directory starting with `index.crates.io`.

**Comment by cadubentzen** [comment]
This also happened to me.
Since the sparse protocol is default as of 1.70.0, this becomes more likely to occur.
Workaround for was setting this in `~/.cargo/config.toml`:
```toml
[registries.crates-io]
protocol = "git"
```

**Comment by PatOConnor43** [comment]
I ran into this using cargo-release 0.24.11. I am also using Rust 1.70.0. I tried adding the `~/.cargo/config.toml` workaround that was suggested above. I wasn't able to successfully `cargo release patch` until I ran `cargo update`. I'm good to go now though.
