### ISSUE TITLE
`-dev` version?

### ISSUE THREAD

**Issue by max-sixty** [crate-ci/cargo-release#685]
Currently the [docs](https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md#bump-level) have:

> alpha, beta, and rc: Add/increment pre-release to your version (1.0.0 -> 1.0.1-rc.1, 1.0.1-dev -> 1.0.1-rc.1, 1.0.1-rc.1 -> 1.0.1-rc.2)

Is it possible to get the `-dev` version with `cargo release`? We'd like to have a post-release version so that running our CLI reports the current version as a development version.

Currently passing `dev`:

```
cargo release version dev -x && cargo release replace -x
error: invalid value 'dev' for '<LEVEL|VERSION>': unexpected character 'd' while parsing major version number
```

We could use `alpha` as a workaround?

**Comment by epage** [comment]
I've corrected the docs to not make a reference to "dev"

The problem with "dev" is it doesn't sort correctly.  According to semver.org, referring to pre-release identifiers:

> Identifiers with letters or hyphens are compared lexically in ASCII sort order.

See https://semver.org/#spec-item-11

**Comment by max-sixty** [comment]
That makes sense, thanks @epage
