### ISSUE TITLE
`cargo release patch` fails with error `object not found - no match for id`

### ISSUE THREAD

**Issue by mmynk** [crate-ci/cargo-release#714]
I'm running the command `cargo release --no-confirm --execute patch` as part of my CI. It always fails with the error:
```
Published netlink-tc v0.0.3 at registry `crates-io`
error: object not found - no match for id (<sha>); class=Odb (9)
Error: Process completed with exit code 101.
```

Even `cargo release --no-confirm --execute --no-publish patch` fails! I'm probably doing something wrong.

Here's my [worflow yml](https://github.com/mmynk/rust-tc/blob/release/.github/workflows/release.yml).

Any help would be highly appreciate. Btw, amazing crate, I considered many before settling on this because it was the simplest and most all-rounded one out there!

**Comment by epage** [comment]
Is the checkout doing a shallow clone?  If so, that would cause the history checks and reports to fail.

**Comment by mmynk** [comment]
Looks so from their [documentation](https://github.com/actions/checkout#checkout-v4), thanks!
