### ISSUE TITLE
Confusing negative forms in config descriptions

### ISSUE THREAD

**Issue by rami3l** [crate-ci/cargo-release#725]
Hi there, and thanks a lot for making this project!

There is a small issue though: in https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md#config-fields I can see that the description of some boolean flags might cause confusions about what `true/false` actually mean:

https://github.com/crate-ci/cargo-release/blob/2df2af97709106c5c8d6f8695bb4b291db34b350/docs/reference.md?plain=1#L113
https://github.com/crate-ci/cargo-release/blob/2df2af97709106c5c8d6f8695bb4b291db34b350/docs/reference.md?plain=1#L121
https://github.com/crate-ci/cargo-release/blob/2df2af97709106c5c8d6f8695bb4b291db34b350/docs/reference.md?plain=1#L127
https://github.com/crate-ci/cargo-release/blob/2df2af97709106c5c8d6f8695bb4b291db34b350/docs/reference.md?plain=1#L133
https://github.com/crate-ci/cargo-release/blob/2df2af97709106c5c8d6f8695bb4b291db34b350/docs/reference.md?plain=1#L134

The list might not be exhaustive but I believe the point has been made.
IMHO it's a bit dangerous to use "don't" in such descriptions, although I have little idea about what to do to fix this either 🤔

**Comment by epage** [comment]
I think this is documentation that went stale with #340.
