### ISSUE TITLE
Using `cargo-release` in diverse monorepo

### ISSUE THREAD

**Issue by azzamsa** [crate-ci/cargo-release#731]
Hi.

Can I use it inside a sub-directory such as:

```
tree --level 1
.
├── .git
├── node-project
├── other-project
├── rust-project
```

Can I tell `cargo-release` to only manage `rust-project` directory?
I always get `error: no packages selected`. None of the commands below worked.

```
# in root directory
cargo release major --manifest-path svc-foo/Cargo.toml --package foo
error: no packages selected

# in `rust-project` sub-directory
cargo release major --manifest-path Cargo.toml --package foo
error: no packages selected

# in `rust-project` sub-directory
file:///.../monorepo/svc-foo#foo@0.5.0
```

I use `cargo-release` for all my stand-alone cargo projects, but I struggle to tune it for Monorepo.
Searching keywords `monerepo`, `subdirectory`, and reading the FAQ doesn't help.

Thank you for `cargo-release` 🎖️

**Comment by epage** [comment]
`cargo release` follows the CLI design of regular cargo commands and is not trying to innovate on that design.  To run it, you either need to be in a rust-project directory or use `--manifest-path` relative to the directory you are currently in.

It sounds like you are wanting it to detect the root of your rust projects and run everything relative to that.  That would be innovating on cargo's design and out of scope.  I'm closing this with that assumption.  If there is a reason we should re-open this, let us know!
