### ISSUE TITLE
Please follow `package.publish` settings in Cargo.toml

### ISSUE THREAD

**Issue by zhengcan** [crate-ci/cargo-release#733]
As introduced in [The Cargo Book](https://doc.rust-lang.org/cargo/reference/manifest.html#the-publish-field), "The publish field can be used to prevent a package from being published to a package registry (like crates.io) by mistake, for instance to keep a package private in a company."

```
[package]
# ...
publish = false
```

Currently, cargo release will bump version for these publish-forbidden crates.
It doesn't make sense.
Please ignore these publish-forbidden crates, and don't publish them.

**Comment by epage** [comment]
If we are publishing them, that is a bug. If we are releasing them, then that is not.

We had a request to default `release` to `package.publish` but after doing so, we got a lot of feedback about how undesirable it was and reverted.

You can disable all release processes for your package via the config.

**Comment by zhengcan** [comment]
Ok. I'll close this issue. THX
