### ISSUE TITLE
If a version already exist add ability to bump to the next version instead of panicking out. 

### ISSUE THREAD

**Issue by veritem** [crate-ci/cargo-release#734]
I'm not sure if this have been discussed before but i wished this package provided a way to bump package's version the next version if the present already exist on the registry. Some packages does it very well like[ this one](https://github.com/antfu/bumpp)  for javascript community. 

If you like this idea. I'm willing to open a pull request addressing it.

**Comment by epage** [comment]
In what scenarios is this happening?

Is this just wanting to run `cargo release -x`?  Or is it that the registry and the repo are out of sync with what versions are released?

**Comment by veritem** [comment]
@epage I was suggesting, instead of it erroring out when package already exists in the registry like the following ...
![Screenshot 2023-12-21 at 11 29 55 PM](https://github.com/crate-ci/cargo-release/assets/53856673/c0a4047f-4cb2-4379-a013-351658c3e469)

To add a flag to enable bumping to the next version automatically.

**Comment by epage** [comment]
Wouldn't that be `cargo release -x patch`?

**Comment by veritem** [comment]
I didn't know that was a thing. Thanks!!
