### ISSUE TITLE
Git User/E-mail is required even if --no-push option is given when running on GitHub runner.

### ISSUE THREAD

**Issue by psandana** [crate-ci/cargo-release#765]
**Summary**

When executing `cargo release` using a version (not a particular step), it requires that Git User/E-mail is set even if `--no-push` and `--no-tag` flags are passed. This is a common scenario on a GitHub pipeline, on which e-mail is not set or invalid.

```bash
cargo release 1.0.0 -p package --registry Registry --execute --no-confirm --no-push --no-tag
```

**Expected**

Previous command should work even if Git User/E-mail is not set, as they are only needed for pushing to remotes

**Comment by epage** [comment]
User name and email are also needed for committing which `cargo release` does.

Note that the requirement is coming from git, and not cargo-release.

**Comment by psandana** [comment]
Didn't noticed that it was complaining by the commit. Thanks for the notice. Closing this issue as invalid one.
